#!/bin/sh

# Add the 'heroku' remote if not here already
git remote show heroku >/dev/null 2>&1 \
  || git remote add heroku git@heroku.com:scratchml.git

# To add
git add .

# To commit
git commit -u -a -m "deploy"

# To deploy: push to heroku
git push heroku master